dist: trusty
sudo: false
language: python
python:
- '2.7'
services:
  - mysql
  - redis
env:
  global:
    - ENV=test
    - PYTHONPATH="$TRAVIS_BUILD_DIR"
    - TEST_DATABASE_URL="mysql://travis:@127.0.0.1/test"
before_install:
  - mysql -e 'CREATE DATABASE test;'
install:
  - make build
  - make db-deploy
  - python test-sudo.py
  - python main.py runtestserver&
script: make test
